### PR TITLE
add null safety

### PR DESCRIPTION
**Pull request by fzyzcjy**
https://github.com/Purus/launch_review/issues/27

### CODE REVIEW

**Comment by fzyzcjy** [comment]
@Purus Maybe a new version can be published to Pub so people can use it :)

**Comment by Purus** [comment]
Thanks for your efforts on this. I will publish the new version by today. I
do see your PR for other repos. Great work buddy.

Thanks,
R.Purusothaman

**Comment by fzyzcjy** [comment]
@Purus 😄

**Comment by RR-Reddy** [comment]
@Purus  and @fzyzcjy   new [issue](https://github.com/Purus/launch_review/issues/29) in version 3.0.0

package not working as expected

**Pull request merged**
